package com.omaster.app.model

enum class SceneType(
    val displayName: String, 
    val description: String,
    val keywords: List<String>,
    val recommendedParams: CameraParams?
) {
    // ==================== 人像类（50种） ====================
    PORTRAIT("人像", "适合人物摄影", listOf("人像", "自拍", "合影", "写真", "肖像", "大头照", "证件照"), CameraParams(hasselblad_hncs = true, master_hdr = "智能")),
    PORTRAIT_NATURAL("自然人像", "自然光人像", listOf("自然光", "柔和光", "窗光", "逆光人像"), CameraParams(hasselblad_hncs = true, ai_scene = true)),
    PORTRAIT_GLOWING("发光人像", "柔光人像", listOf("柔光", "发光", "梦幻", "仙气"), CameraParams(saturation = 12, clarity = 8)),
    PORTRAIT_MOOD("情绪人像", "有氛围感的人像", listOf("情绪", "氛围", "暗调", "情绪人像"), CameraParams(brightness = -5, contrast = 15, saturation = 8)),
    PORTRAIT_RETRO("复古人像", "复古风格人像", listOf("复古", "怀旧", "胶片感", "颗粒"), CameraParams(saturation = 5, contrast = 10, warmth = 8)),
    PORTRAIT_HIGHKEY("高调人像", "明亮清新人像", listOf("高调", "明亮", "清新", "日系"), CameraParams(brightness = 15, contrast = -5, saturation = 10)),
    PORTRAIT_LOWKEY("低调人像", "深沉有质感人像", listOf("低调", "深沉", "质感", "电影感"), CameraParams(brightness = -10, contrast = 20, saturation = 5)),
    PORTRAIT_SOFT("柔美人像", "柔和过渡人像", listOf("柔美", "奶油肌", "通透"), CameraParams(brightness = 12, saturation = 5, clarity = 3)),
    PORTRAIT_DRAMATIC("戏剧人像", "强烈对比人像", listOf("戏剧", "强烈", "对比", "张力"), CameraParams(contrast = 25, saturation = 8, brightness = -3)),
    GROUP_PHOTO("合影", "多人合影", listOf("合影", "团体", "集体照", "聚会"), CameraParams(hdr = true, ai_scene = true)),
    KIDS("儿童", "儿童摄影", listOf("儿童", "宝宝", "小孩", "萌娃"), CameraParams(saturation = 15, brightness = 10, ai_scene = true)),
    WEDDING("婚礼", "婚礼摄影", listOf("婚礼", "婚纱", "典礼", "婚庆"), CameraParams(hasselblad_hncs = true, master_hdr = "智能")),
    MATERNITY("孕妇", "孕妇摄影", listOf("孕妇", "孕照", "孕期"), CameraParams(saturation = 12, brightness = 8, clarity = 5)),
    PET("宠物", "宠物摄影", listOf("宠物", "猫", "狗", "小动物"), CameraParams(ai_scene = true, saturation = 10)),
    SELFIE("自拍", "自拍摄影", listOf("自拍", "前置", "美颜", "大头照"), CameraParams(ai_scene = true, brightness = 10, clarity = 5)),
    COSPLAY("Cosplay", "角色扮演摄影", listOf("Cosplay", "cos", "角色扮演", "二次元"), CameraParams(saturation = 15, contrast = 12, clarity = 10)),
    FASHION("时尚人像", "时尚杂志风格", listOf("时尚", "杂志", "大片", "Fashion"), CameraParams(contrast = 18, saturation = 10, clarity = 12)),
    SPORTS_PORTRAIT("运动人像", "运动中的人物", listOf("运动人像", "动态", "跑步", "健身"), CameraParams(ai_scene = true, shutter_speed = "1/500")),
    PORTRAIT_BABY("婴儿", "婴儿摄影", listOf("婴儿", "新生儿", "满月", "百天"), CameraParams(brightness = 15, saturation = 10, ai_scene = true)),
    PORTRAIT_SENIOR("长者", "老年摄影", listOf("老人", "长者", "全家福", "纪念"), CameraParams(brightness = 10, saturation = 8, warmth = 5)),
    PORTRAIT_COUPLE("情侣", "情侣摄影", listOf("情侣", "恋人", "爱情", "甜蜜"), CameraParams(hasselblad_hncs = true, saturation = 12, warmth = 8)),
    PORTRAIT_FAMILY("家庭", "家庭摄影", listOf("家庭", "全家福", "亲子", "家人"), CameraParams(hdr = true, ai_scene = true)),
    PORTRAIT_STUDIO("棚拍", "摄影棚人像", listOf("棚拍", "灯光", "专业", "影楼"), CameraParams(master_hdr = "智能", contrast = 12, clarity = 10)),
    PORTRAIT_OUTDOOR("外景人像", "户外人像", listOf("外景", "户外", "自然光", "外景拍摄"), CameraParams(hdr = true, ai_scene = true)),
    PORTRAIT_NIGHT("夜景人像", "夜间人像", listOf("夜景人像", "夜拍", "灯光人像"), CameraParams(ai_scene = true, brightness = 5)),
    PORTRAIT_BACKLIGHT("逆光人像", "逆光拍摄", listOf("逆光", "剪影", "背光"), CameraParams(master_hdr = "智能", brightness = 10)),
    PORTRAIT_PROFILE("侧脸", "侧面人像", listOf("侧脸", "轮廓", "剪影", "profile"), CameraParams(contrast = 15, saturation = 8)),
    PORTRAIT_CLOSEUP("特写", "人像特写", listOf("特写", "近景", "细节", "局部"), CameraParams(clarity = 15, contrast = 10)),
    PORTRAIT_FULL("全身", "全身人像", listOf("全身", "全身照", "全身人像"), CameraParams(hdr = true, ai_scene = true)),
    PORTRAIT_HALF("半身", "半身人像", listOf("半身", "半身照", "上半身"), CameraParams(brightness = 8, saturation = 10)),
    PORTRAIT_FASHION_EDITORIAL("时尚大片", "杂志大片风格", listOf("时尚大片", "Editorial", "高级感"), CameraParams(contrast = 20, saturation = 12, clarity = 15)),
    PORTRAIT_BEAUTY("美妆", "美妆人像", listOf("美妆", "妆容", "彩妆", "护肤"), CameraParams(brightness = 12, saturation = 8, clarity = 8)),
    PORTRAIT_ART("艺术人像", "艺术创作", listOf("艺术", "创意", "Concept", "Fine Art"), CameraParams(contrast = 18, saturation = 10, brightness = -3)),
    PORTRAIT_DANCE("舞蹈", "舞蹈摄影", listOf("舞蹈", "舞者", "动态", "舞姿"), CameraParams(shutter_speed = "1/500", ai_scene = true)),
    PORTRAIT_MUSIC("音乐人", "音乐人像", listOf("音乐", "乐器", "乐队", "歌手"), CameraParams(contrast = 15, saturation = 12)),
    PORTRAIT_ACTOR("演员", "演员定妆", listOf("演员", "定妆", "角色", "戏剧"), CameraParams(brightness = 8, saturation = 10, contrast = 12)),
    PORTRAIT_MODEL("模特", "模特摄影", listOf("模特", "Model", "走秀", "时尚"), CameraParams(contrast = 18, saturation = 12, clarity = 12)),
    PORTRAIT_BUSINESS("商务", "商务人像", listOf("商务", "职业", "西装", "职场"), CameraParams(contrast = 12, saturation = 5, clarity = 10)),
    PORTRAIT_AVATAR("头像", "头像摄影", listOf("头像", "证件照", "职业照", "头像照"), CameraParams(brightness = 10, contrast = 8, saturation = 5)),
    PORTRAIT_GRADUATION("毕业", "毕业照", listOf("毕业", "毕业照", "学士服", "校园"), CameraParams(hdr = true, ai_scene = true)),
    PORTRAIT_CHILDREN_STUDIO("儿童棚拍", "儿童室内摄影", listOf("儿童棚拍", "室内儿童", "影棚"), CameraParams(brightness = 15, saturation = 12, ai_scene = true)),
    PORTRAIT_NEWBORN("新生儿", "新生儿摄影", listOf("新生儿", "满月照", "婴儿"), CameraParams(brightness = 12, saturation = 8, warmth = 5)),
    PORTRAIT_MILITARY("军装", "军装人像", listOf("军装", "制服", "军人", "警服"), CameraParams(contrast = 15, saturation = 8, clarity = 10)),
    PORTRAIT_NURSE("医护", "医护人像", listOf("医护", "护士", "医生", "白大褂"), CameraParams(brightness = 10, saturation = 5, contrast = 8)),
    PORTRAIT_STUDENT("学生", "学生人像", listOf("学生", "校服", "校园", "青春"), CameraParams(brightness = 12, saturation = 10, warmth = 5)),
    PORTRAIT_OLDER_ADULT("中老年", "中老年人像", listOf("中老年", "成熟", "稳重", "岁月")),
    PORTRAIT_TEEN("青少年", "青少年人像", listOf("青少年", "青春", "活力", "学生")),
    PORTRAIT_INFLUENCER("博主", "网红博主", listOf("博主", "网红", "自媒体", "直播")),
    PORTRAIT_ARTIST("艺术家", "艺术家人像", listOf("艺术家", "创作者", "设计师", "画家")),

    // ==================== 风景类（60种） ====================
    LANDSCAPE("风景", "户外风景摄影", listOf("风景", "山川", "自然", "scenery"), CameraParams(hdr = true, ai_scene = true)),
    MOUNTAIN("山脉", "山景摄影", listOf("山", "山脉", "峰峦", "高原"), CameraParams(contrast = 15, clarity = 12, saturation = 10)),
    OCEAN("海洋", "海边摄影", listOf("海", "海洋", "沙滩", "波浪"), CameraParams(saturation = 15, brightness = 5, hdr = true)),
    LAKE("湖泊", "湖景摄影", listOf("湖", "湖泊", "倒影", "静谧"), CameraParams(saturation = 12, clarity = 10, brightness = 5)),
    FOREST("森林", "森林摄影", listOf("森林", "树木", "绿植", "林间"), CameraParams(saturation = 15, clarity = 8, ai_scene = true)),
    FLOWER("花卉", "花卉摄影", listOf("花", "花卉", "植物", "花园"), CameraParams(saturation = 20, clarity = 15, macro = true)),
    SKY("天空", "天空云彩", listOf("天空", "云", "蓝天", "云彩"), CameraParams(brightness = 10, contrast = 12, saturation = 8)),
    SNOW("雪景", "雪地摄影", listOf("雪", "雪景", "冬季", "冰雪"), CameraParams(brightness = 15, contrast = 5, saturation = 3)),
    DESERT("沙漠", "沙漠摄影", listOf("沙漠", "沙丘", "戈壁", "荒漠"), CameraParams(saturation = 10, contrast = 15, warmth = 12)),
    WATERFALL("瀑布", "瀑布摄影", listOf("瀑布", "水流", "溪流", "江河"), CameraParams(contrast = 12, clarity = 15, brightness = 3)),
    STARS("星空", "星空摄影", listOf("星空", "星星", "银河", "夜空"), CameraParams(brightness = -5, contrast = 15, saturation = 8)),
    RAINBOW("彩虹", "彩虹摄影", listOf("彩虹", "虹", "光谱"), CameraParams(saturation = 25, brightness = 8, hdr = true)),
    SUNRISE("日出", "日出摄影", listOf("日出", "朝阳", "晨曦", "破晓"), CameraParams(warmth = 20, brightness = 8, saturation = 15)),
    SUNSET("日落", "日落摄影", listOf("日落", "夕阳", "黄昏", "晚霞"), CameraParams(warmth = 25, saturation = 20, brightness = 5)),
    CLOUDS("云海", "云海摄影", listOf("云海", "云雾", "仙境", "山间云雾"), CameraParams(contrast = 10, brightness = 8, clarity = 12)),
    BEACH("海滩", "海滨摄影", listOf("海滩", "海边", "沙滩", "椰树"), CameraParams(saturation = 18, brightness = 8, hdr = true)),
    RIVER("河流", "河流摄影", listOf("河", "河流", "溪水", "江水"), CameraParams(saturation = 12, clarity = 12, brightness = 5)),
    GLACIER("冰川", "冰川摄影", listOf("冰川", "冰山", "极地", "蓝冰"), CameraParams(saturation = 5, contrast = 15, brightness = 8)),
    CANYON("峡谷", "峡谷摄影", listOf("峡谷", "丹霞", "地貌", "奇观"), CameraParams(contrast = 18, warmth = 8, clarity = 12)),
    VOLCANO("火山", "火山摄影", listOf("火山", "熔岩", "喷发", "地质")),
    WATERFALL_LOW("低角度瀑布", "仰视瀑布", listOf("仰视瀑布", "低角度", "水流")),
    FOG("雾景", "雾中风景", listOf("雾", "雾气", "朦胧", "迷雾")),
    MIST("薄雾", "薄雾风景", listOf("薄雾", "轻雾", "朦胧美", "Morning Mist")),
    TWILIGHT("暮光", "暮光时刻", listOf("暮光", "黄昏", "Blue Hour", "暮色")),
    GOLDEN_HOUR("黄金时刻", "黄金时段", listOf("黄金时刻", "Golden Hour", "日出后", "日落前")),
    BLUE_HOUR("蓝色时刻", "蓝调时刻", listOf("蓝色时刻", "Blue Hour", "蓝调")),
    WINTER_LANDSCAPE("冬景", "冬季风景", listOf("冬景", "冬天", "严寒", "冰雪世界")),
    SPRING_LANDSCAPE("春景", "春季风景", listOf("春景", "春天", "花开", "复苏")),
    SUMMER_LANDSCAPE("夏景", "夏季风景", listOf("夏景", "夏天", "翠绿", "炎热")),
    AUTUMN_LANDSCAPE("秋景", "秋季风景", listOf("秋景", "秋天", "金黄", "落叶")),
    MEADOW("草地", "草原风景", listOf("草原", "草地", "牧场", "野花")),
    PRAIRIE("大草原", "辽阔草原", listOf("大草原", "草原风光", "辽阔", "牧民")),
    WETLAND("湿地", "湿地风景", listOf("湿地", "沼泽", "候鸟", "生态")),
    COASTLINE("海岸线", "海岸风景", listOf("海岸线", "沿海", "礁石", "潮汐")),
    ISLAND("海岛", "海岛风景", listOf("海岛", "岛屿", "度假", "热带")),
    CLIFF("悬崖", "悬崖峭壁", listOf("悬崖", "峭壁", "险峻", "边缘")),
    VALLEY("山谷", "山谷风景", listOf("山谷", "峡谷", "沟壑", "纵深")),
    PLATEAU("高原", "高原风景", listOf("高原", "海拔", "缺氧", "辽阔")),
    ALPINE("高山", "高山风景", listOf("高山", "阿尔卑斯", "雪峰", "攀登")),
    TROPICAL("热带", "热带风光", listOf("热带", "雨林", "椰子树", "沙滩")),
    SUBTROPICAL("亚热带", "亚热带风光", listOf("亚热带", "温润", "常绿", "雨林")),
    TEMPERATE("温带", "温带风景", listOf("温带", "四季分明", "落叶", "气候")),
    ARCTIC("极地", "北极风光", listOf("北极", "极地", "极光", "冰原")),
    TUNDRA("苔原", "苔原景观", listOf("苔原", "冻土", "寒带", "植被")),
    RAINFOREST("雨林", "热带雨林", listOf("雨林", "丛林", "茂密", "生物")),
    CORAL_REEF("珊瑚礁", "海底珊瑚", listOf("珊瑚", "海底", "潜水", "海洋")),
    WATER_REFLECTION("水面倒影", "倒影摄影", listOf("倒影", "镜像", "对称", "水面")),
    SKY_REFLECTION("天空倒影", "天空倒影", listOf("天空倒影", "镜像天空", "对称")),
    MOUNTAIN_REFLECTION("山影", "山的倒影", listOf("山影", "山倒影", "水中山")),
    TREE_REFLECTION("树影", "树的倒影", listOf("树影", "树倒影", "水中树")),
    LAKE_ISLAND("湖中小岛", "湖岛风景", listOf("湖岛", "湖心岛", "小岛")),
    RIVER_BEND("河流弯道", "河湾风景", listOf("河湾", "弯道", "S形河")),
    WATERFALL_PANO("瀑布全景", "瀑布全景图", listOf("瀑布全景", "广角瀑布")),
    MOUNTAIN_RANGE("山脉连绵", "群山风景", listOf("群山", "连绵山脉", "层峦叠嶂")),
    HILL("丘陵", "丘陵风景", listOf("丘陵", "起伏", "平缓", "田园")),
    PLAIN("平原", "平原风景", listOf("平原", "辽阔", "坦荡", "麦田")),
    DELTA("三角洲", "三角洲景观", listOf("三角洲", "河口", "冲积平原")),
    ESTUARY("河口", "河口景观", listOf("河口", "入海口", "潮汐")),
    BAY("海湾", "海湾风景", listOf("海湾", "港湾", "避风港")),
    PENINSULA("半岛", "半岛风景", listOf("半岛", "陆地延伸", "三面环海")),
    CAPE("海角", "海角风景", listOf("海角", "岬角", "海岬")),

    // ==================== 城市建筑类（50种） ====================
    ARCHITECTURE("建筑", "建筑摄影", listOf("建筑", "楼房", "大厦", "现代建筑"), CameraParams(contrast = 15, clarity = 12, ai_scene = true)),
    CITY_NIGHT("城市夜景", "都市夜景", listOf("城市夜景", "霓虹", "灯火", "夜景"), CameraParams(brightness = -8, contrast = 20, saturation = 15)),
    STREET("街头", "街头摄影", listOf("街头", "街道", "城市", "纪实"), CameraParams(contrast = 12, clarity = 8, blackWhite = false)),
    LANDMARK("地标", "城市地标", listOf("地标", "标志性建筑", "纪念碑", "塔"), CameraParams(clarity = 15, contrast = 12, hdr = true)),
    INTERIOR("室内", "室内空间", listOf("室内", "房间", "家居", "装修"), CameraParams(brightness = 8, saturation = 5, ai_scene = true)),
    ROOM("空间", "室内设计", listOf("空间", "装修", "北欧", "简约"), CameraParams(saturation = 8, brightness = 10, contrast = 5)),
    OFFICE("办公", "办公空间", listOf("办公室", "工作", "写字楼", "商务"), CameraParams(contrast = 8, saturation = 5, brightness = 5)),
    SHOP("商铺", "商业空间", listOf("商店", "店铺", "橱窗", "商业"), CameraParams(saturation = 12, brightness = 8, contrast = 8)),
    RESTAURANT("餐厅", "餐饮空间", listOf("餐厅", "饭店", "咖啡厅", "餐饮"), CameraParams(warmth = 10, saturation = 12, brightness = 5)),
    HOTEL("酒店", "酒店空间", listOf("酒店", "民宿", "客房", "旅馆"), CameraParams(brightness = 10, saturation = 5, contrast = 5)),
    BRIDGE("桥梁", "桥梁摄影", listOf("桥", "桥梁", "跨海大桥", "悬索桥"), CameraParams(contrast = 15, clarity = 12, hdr = true)),
    TOWER("塔楼", "塔式建筑", listOf("塔", "塔楼", "电视塔", "地标"), CameraParams(contrast = 12, clarity = 15, saturation = 8)),
    MODERN_ARCH("现代建筑", "现代风格建筑", listOf("现代建筑", "摩天大楼", "玻璃幕墙")),
    CLASSICAL_ARCH("古典建筑", "古典风格建筑", listOf("古典建筑", "欧式", "复古建筑")),
    TRADITIONAL_ARCH("传统建筑", "中式传统建筑", listOf("传统建筑", "中式", "四合院", "飞檐")),
    HISTORIC_ARCH("历史建筑", "历史建筑", listOf("历史建筑", "古迹", "遗址", "文物")),
    INDUSTRIAL_ARCH("工业建筑", "工业风建筑", listOf("工业建筑", "厂房", "仓库", "Loft")),
    RESIDENTIAL_ARCH("住宅建筑", "居住建筑", listOf("住宅", "公寓", "小区", "别墅")),
    COMMERCIAL_ARCH("商业建筑", "商业综合体", listOf("商业", "商场", "购物中心", "综合体")),
    CULTURAL_ARCH("文化建筑", "文化场馆", listOf("文化建筑", "博物馆", "美术馆", "剧院")),
    RELIGIOUS_ARCH("宗教建筑", "宗教场所", listOf("宗教建筑", "教堂", "寺庙", "清真寺")),
    GOVERNMENT_ARCH("政府建筑", "政府机构", listOf("政府建筑", "市政厅", "议会", "行政")),
    EDUCATIONAL_ARCH("教育建筑", "教育机构", listOf("教育建筑", "学校", "大学", "图书馆")),
    HOSPITAL_ARCH("医疗建筑", "医疗机构", listOf("医疗建筑", "医院", "诊所", "卫生")),
    SPORTS_ARCH("体育建筑", "体育场馆", listOf("体育建筑", "体育馆", "体育场", "游泳馆")),
    TRANSPORT_ARCH("交通建筑", "交通设施", listOf("交通建筑", "车站", "机场", "地铁站")),
    BRIDGE_SUSPENSION("悬索桥", "悬索桥梁", listOf("悬索桥", "斜拉桥", "大跨度")),
    BRIDGE_ARCH("拱桥", "拱式桥梁", listOf("拱桥", "石拱桥", "古桥")),
    BRIDGE_CANTILEVER("悬臂桥", "悬臂桥梁", listOf("悬臂桥", "桁架桥")),
    BRIDGE_CABLE_STAYED("斜拉桥", "斜拉桥梁", listOf("斜拉桥", "拉索桥")),
    TOWER_EIFFEL("埃菲尔式", "铁塔风格", listOf("铁塔", "埃菲尔", "观景塔")),
    TOWER_SKYSCRAPER("摩天塔", "超高层建筑", listOf("摩天楼", "超高层", "地标塔")),
    TOWER_CLOCK("钟楼", "钟楼建筑", listOf("钟楼", "时钟塔", "报时")),
    TOWER_OBSERVATION("观景塔", "观景平台", listOf("观景塔", "瞭望塔", "俯瞰")),
    STREET_NIGHT("夜间街头", "夜间街道", listOf("夜街", "路灯", "夜市")),
    STREET_DAY("日间街头", "白天街道", listOf("街道", "行人", "日常")),
    STREET_RAIN("雨天街头", "雨中街道", listOf("雨天街", "雨景", "倒影")),
    STREET_SNOW("雪天街头", "雪中街道", listOf("雪街", "雪景", "冬日")),
    URBAN_CANYON("城市峡谷", "高楼峡谷", listOf("城市峡谷", "高楼间", "阴影")),
    CITY_PANORAMA("城市全景", "全景城市", listOf("城市全景", "天际线", "广角")),
    CITY_AERIAL("城市航拍", "空中城市", listOf("城市航拍", "鸟瞰", "上帝视角")),
    CITY_SUNRISE("城市日出", "城市清晨", listOf("城市日出", "晨雾", "苏醒")),
    CITY_SUNSET("城市日落", "城市黄昏", listOf("城市日落", "夕阳", "晚霞")),
    CITY_LIGHTS("城市灯光", "灯火辉煌", listOf("城市灯光", "夜景", "璀璨")),
    CITY_REFLECTION("城市倒影", "城市水中倒影", listOf("城市倒影", "水中城", "镜像")),
    NEIGHBORHOOD("街区", "城市街区", listOf("街区", "胡同", "里弄", "小巷")),
    MARKET("集市", "市场街区", listOf("集市", "市集", "步行街", "摊贩")),
    PARK("公园", "城市公园", listOf("公园", "绿地", "休闲", "广场")),
    SQUARE("广场", "城市广场", listOf("广场", "市民广场", "地标广场")),
    MONUMENT("纪念碑", "纪念建筑", listOf("纪念碑", "雕像", "纪念物")),
    FOUNTAIN("喷泉", "喷泉景观", listOf("喷泉", "水景", "雕塑")),

    // ==================== 美食类（50种） ====================
    FOOD("美食", "美食摄影", listOf("美食", "菜肴", "料理", "food"), CameraParams(saturation = 18, brightness = 5, ai_scene = true)),
    DISH("菜品", "中式菜品", listOf("菜品", "中餐", "炒菜", "佳肴"), CameraParams(saturation = 20, warmth = 5, brightness = 8)),
    CAKE("甜点", "蛋糕甜品", listOf("蛋糕", "甜点", "甜品", "下午茶"), CameraParams(saturation = 22, brightness = 10, clarity = 12)),
    DRINK("饮品", "饮料咖啡", listOf("饮品", "咖啡", "饮料", "奶茶"), CameraParams(saturation = 15, brightness = 8, warmth = 8)),
    SUSHI("寿司", "日料摄影", listOf("寿司", "日料", "刺身", "日本料理"), CameraParams(saturation = 12, contrast = 8, brightness = 5)),
    BBQ("烧烤", "烧烤美食", listOf("烧烤", "烤肉", "撸串", "BBQ"), CameraParams(warmth = 12, saturation = 15, contrast = 8)),
    NOODLE("面食", "面食摄影", listOf("面条", "面食", "拉面", "米粉"), CameraParams(saturation = 10, warmth = 8, brightness = 5)),
    VEGETABLE("蔬果", "蔬菜水果", listOf("蔬菜", "水果", "沙拉", "健康"), CameraParams(saturation = 25, clarity = 12, brightness = 8)),
    HOTPOT("火锅", "火锅摄影", listOf("火锅", "川锅", "麻辣", "涮肉"), CameraParams(saturation = 18, warmth = 15, brightness = 5)),
    BAKING("烘焙", "烘焙甜点", listOf("烘焙", "面包", "饼干", "马卡龙"), CameraParams(warmth = 12, saturation = 15, brightness = 8)),
    DESSERT("甜品", "西式甜品", listOf("甜品", "西点", "精致", "Pastry")),
    ICE_CREAM("冰淇淋", "冷饮甜点", listOf("冰淇淋", "雪糕", "冰棒", "冷饮")),
    CHOCOLATE("巧克力", "巧克力甜点", listOf("巧克力", "可可", "甜品", "Chocolate")),
    FRUIT("水果", "水果摄影", listOf("水果", "鲜果", "果盘", "新鲜")),
    SALAD("沙拉", "沙拉轻食", listOf("沙拉", "轻食", "健康", "Salad")),
    STEAK("牛排", "西餐牛排", listOf("牛排", "西餐", "Beef", "Steak")),
    PASTA("意面", "意大利面", listOf("意面", "Pasta", "意大利面", "西餐")),
    PIZZA("披萨", "披萨饼", listOf("披萨", "Pizza", "饼", "西餐")),
    SANDWICH("三明治", "三明治", listOf("三明治", "Sandwich", "快餐")),
    SOUP("汤品", "汤类美食", listOf("汤", "汤品", "Soup", "羹")),
    SEAFOOD("海鲜", "海鲜料理", listOf("海鲜", "鱼虾", "Ocean", "Seafood")),
    RICE("米饭", "米饭料理", listOf("米饭", "Rice", "主食", "寿司饭")),
    CURRY("咖喱", "咖喱料理", listOf("咖喱", "Curry", "香料", "印度")),
    RAMEN("拉面", "日式拉面", listOf("拉面", "Ramen", "日式", "汤面")),
    UDON("乌冬", "乌冬面", listOf("乌冬", "Udon", "日式", "宽面")),
    SOBA("荞麦", "荞麦面", listOf("荞麦", "Soba", "日式", "杂粮")),
    DUMPLING("饺子", "中式饺子", listOf("饺子", "Dumpling", "水饺", "蒸饺")),
    DIM_SUM("点心", "港式点心", listOf("点心", "Dim Sum", "早茶", "粤菜")),
    DIM_SUM_DIMSUM("港式早茶", "港式点心", listOf("早茶", "饮茶", "点心")),
    HOT_POT_CHINESE("中式火锅", "中国火锅", listOf("火锅", "涮肉", "麻辣")),
    HOT_POT_THAI("泰式火锅", "泰国火锅", listOf("泰式火锅", "冬阴功", "酸辣")),
    HOT_POT_KOREAN("韩式火锅", "韩国火锅", listOf("韩式火锅", "部队锅", "泡菜")),
    GRILL("烤肉", "韩式烤肉", listOf("烤肉", "韩式", "Grill", "BBQ")),
    SUSHI_SASHIMI("刺身", "生鱼片", listOf("刺身", "Sashimi", "生鱼片")),
    TEMAKI("手卷", "寿司手卷", listOf("手卷", "Temaki", "寿司卷")),
    MAKI("寿司卷", "卷寿司", listOf("寿司卷", "Maki", "Roll")),
    ONIGIRI("饭团", "日式饭团", listOf("饭团", "Onigiri", "日式")),
    TEMPURA("天妇罗", "日式炸物", listOf("天妇罗", "Tempura", "油炸")),
    TERIYAKI("照烧", "照烧料理", listOf("照烧", "Teriyaki", "日式")),
    SUSHI_NIGIRI("握寿司", "手握寿司", listOf("握寿司", "Nigiri", "日式")),
    CAFE("咖啡", "咖啡馆", listOf("咖啡", "Cafe", "Espresso", "Latte")),
    TEA("茶饮", "茶饮文化", listOf("茶", "Tea", "茶道", "中式茶")),
    COCKTAIL("鸡尾酒", "调制酒", listOf("鸡尾酒", "Cocktail", "调酒")),
    WINE("红酒", "葡萄酒", listOf("红酒", "Wine", "葡萄酒", "品酒")),
    BEER("啤酒", "啤酒", listOf("啤酒", "Beer", "精酿", "IPA")),
    WHISKEY("威士忌", "威士忌", listOf("威士忌", "Whiskey", "烈酒")),
    SAKE("清酒", "日本清酒", listOf("清酒", "Sake", "日式", "米酒")),
    DIM_SUM_HAR_GOW("虾饺", "港式虾饺", listOf("虾饺", "Har Gow", "点心")),
    DIM_SUM_SIU_MAI("烧卖", "港式烧卖", listOf("烧卖", "Siu Mai", "点心")),
    DIM_SUM_CHAR_SIU("叉烧包", "叉烧包", listOf("叉烧包", "Char Siu", "点心")),

    // ==================== 自然生态类（50种） ====================
    NATURE("自然", "自然生态", listOf("自然", "生态", "户外", "nature"), CameraParams(saturation = 12, ai_scene = true, hdr = true)),
    PLANT("植物", "植物摄影", listOf("植物", "绿植", "盆栽", "花卉"), CameraParams(saturation = 18, clarity = 12, macro = true)),
    TREE("树木", "树木摄影", listOf("树", "树木", "森林", "林间"), CameraParams(saturation = 12, contrast = 8, clarity = 10)),
    GRASS("草地", "草坪草地", listOf("草地", "草坪", "绿草", "草原"), CameraParams(saturation = 15, brightness = 8, ai_scene = true)),
    BUG("昆虫", "昆虫微距", listOf("昆虫", "虫子", "蚂蚁", "蝴蝶"), CameraParams(macro = true, clarity = 18, contrast = 10)),
    BIRD("鸟类", "鸟类摄影", listOf("鸟", "鸟类", "飞鸟", "天鹅"), CameraParams(contrast = 12, clarity = 15, ai_scene = true)),
    AQUARIUM("水族", "水下世界", listOf("鱼", "水族", "珊瑚", "海洋生物"), CameraParams(saturation = 18, brightness = 8, hdr = true)),
    ZOO("动物园", "动物园摄影", listOf("动物园", "动物", "狮子", "老虎"), CameraParams(contrast = 10, saturation = 12, ai_scene = true)),
    GARDEN("园林", "园林景观", listOf("园林", "庭院", "苏州园林", "古典"), CameraParams(saturation = 12, warmth = 5, clarity = 10)),
    FARM("农场", "农业摄影", listOf("农场", "农田", "麦田", "稻田"), CameraParams(saturation = 15, warmth = 8, contrast = 10)),
    ANIMAL_WILD("野生动物", "野外动物", listOf("野生动物", "自然", "野外", "Safari")),
    ANIMAL_DOMESTIC("家养动物", "宠物家畜", listOf("家养动物", "宠物", "家畜")),
    ANIMAL_MARINE("海洋动物", "海洋生物", listOf("海洋动物", "鲸鱼", "海豚", "鲨鱼")),
    ANIMAL_AIR("飞行动物", "飞禽", listOf("飞行动物", "鸟类", "飞鸟", "老鹰")),
    ANIMAL_INSECT("昆虫", "昆虫微距", listOf("昆虫", "蝴蝶", "蜜蜂", "甲虫")),
    ANIMAL_REPTILE("爬行动物", "爬行动物", listOf("爬行动物", "蛇", "蜥蜴", "乌龟")),
    ANIMAL_AMPHIBIAN("两栖动物", "两栖类", listOf("两栖动物", "青蛙", "蟾蜍")),
    ANIMAL_MAMMAL("哺乳动物", "哺乳类", listOf("哺乳动物", "狮子", "大象", "猴子")),
    ANIMAL_BIRD_SMALL("小型鸟类", "小鸟", listOf("小鸟", "麻雀", "燕子", "鸽子")),
    ANIMAL_BIRD_LARGE("大型鸟类", "大鸟", listOf("大鸟", "鹰", "鹫", "鹤")),
    ANIMAL_WATERFOWL("水鸟", "水禽", listOf("水鸟", "鸭子", "天鹅", "鸳鸯")),
    ANIMAL_FISH("鱼类", "鱼类", listOf("鱼", "金鱼", "锦鲤", "热带鱼")),
    ANIMAL_CRUSTACEAN("甲壳类", "甲壳动物", listOf("甲壳类", "虾", "蟹", "龙虾")),
    ANIMAL_MOLLUSK("软体动物", "软体类", listOf("软体动物", "蜗牛", "贝壳", "章鱼")),
    ANIMAL_ARACHNID("蛛形类", "蜘蛛", listOf("蜘蛛", "蝎子", "蜱虫")),
    PLANT_FLOWER("花卉", "开花植物", listOf("花卉", "花", "玫瑰", "牡丹")),
    PLANT_TREE_DECIDUOUS("落叶树", "落叶乔木", listOf("落叶树", "梧桐", "枫叶", "银杏")),
    PLANT_TREE_EVERGREEN("常绿树", "常绿乔木", listOf("常绿树", "松树", "柏树", "杉树")),
    PLANT_SHRUB("灌木", "灌木丛", listOf("灌木", "灌木", "绿篱", "月季")),
    PLANT_VINE("藤蔓", "藤本植物", listOf("藤蔓", "葡萄藤", "爬山虎", "牵牛花")),
    PLANT_SUCCULENT("多肉", "多肉植物", listOf("多肉", "Succulent", "仙人掌", "景天")),
    PLANT_FERN("蕨类", "蕨类植物", listOf("蕨类", "蕨", "苔藓", "阴生")),
    PLANT_AQUATIC("水生植物", "水草", listOf("水生植物", "荷花", "睡莲", "水草")),
    PLANT_BAMBOO("竹类", "竹子", listOf("竹子", "竹林", "竹"), CameraParams(saturation = 15, clarity = 10)),
    PLANT_GRASSLAND("草原植物", "草原植被", listOf("草原植物", "牧草", "野花")),
    PLANT_DESERT("沙漠植物", "沙漠植被", listOf("沙漠植物", "仙人掌", "耐旱")),
    PLANT_ALPINE("高山植物", "高山植被", listOf("高山植物", "雪莲", "苔藓")),
    PLANT_TROPICAL("热带植物", "热带植被", listOf("热带植物", "椰树", "棕榈", "芭蕉")),
    PLANT_MEDICINAL("药用植物", "中草药", listOf("药用植物", "中药", "草药")),
    PLANT_FRUIT_TREE("果树", "水果树", listOf("果树", "苹果", "柑橘", "桃树")),
    PLANT_VEGETABLE("蔬菜", "蔬菜植物", listOf("蔬菜", "白菜", "番茄", "黄瓜")),
    PLANT_GRAIN("粮食作物", "谷物", listOf("粮食作物", "水稻", "小麦", "玉米")),
    PLANT_CASH_CROP("经济作物", "经济植物", listOf("经济作物", "棉花", "茶叶", "烟草")),
    ECOSYSTEM_FOREST("森林生态", "森林系统", listOf("森林生态", "生态系统", "林地")),
    ECOSYSTEM_WETLAND("湿地生态", "湿地系统", listOf("湿地生态", "沼泽", "候鸟栖息地")),
    ECOSYSTEM_OCEAN("海洋生态", "海洋系统", listOf("海洋生态", "珊瑚礁", "海洋保护")),
    ECOSYSTEM_DESERT("沙漠生态", "荒漠系统", listOf("沙漠生态", "戈壁", "耐旱植物")),
    ECOSYSTEM_ALPINE("高山生态", "高山系统", listOf("高山生态", "高原", "苔原")),
    ECOSYSTEM_FARM("农田生态", "农业系统", listOf("农田生态", "耕地", "作物")),

    // ==================== 创意类（50种） ====================
    MACRO("微距", "微距摄影", listOf("微距", "特写", "细节", "macro"), CameraParams(macro = true, clarity = 20, contrast = 12)),
    BLACK_WHITE("黑白", "黑白摄影", listOf("黑白", "单色", "Mono", "B&W"), CameraParams(blackWhite = true, contrast = 15, clarity = 10)),
    VINTAGE("复古", "复古风格", listOf("复古", "怀旧", "胶片", "Vintage"), CameraParams(saturation = 5, contrast = 12, warmth = 15)),
    CINEMATIC("电影感", "电影色调", listOf("电影感", "Cinematic", "电影", "好莱坞"), CameraParams(contrast = 18, saturation = 8, brightness = -3)),
    CYBERPUNK("赛博朋克", "科技感色调", listOf("赛博朋克", "科技", "霓虹", "Cyberpunk"), CameraParams(saturation = 25, contrast = 20, hue = 15)),
    PAINTING("油画感", "油画效果", listOf("油画", "绘画", "艺术", "Painting"), CameraParams(saturation = 8, contrast = 5, clarity = 15)),
    MINIMAL("极简", "极简风格", listOf("极简", "简约", "Less", "Minimal"), CameraParams(saturation = 3, contrast = 8, brightness = 10)),
    NEON("霓虹", "霓虹灯光", listOf("霓虹", "灯光", "夜店", "Neon"), CameraParams(saturation = 25, contrast = 15, brightness = -5)),
    FILM("胶片", "胶片质感", listOf("胶片", "Film", "颗粒", "Kodak"), CameraParams(saturation = 8, contrast = 10, grain = true)),
    RETRO80S("80年代", "80年代风格", listOf("80s", "复古", "迪斯科", "年代"), CameraParams(saturation = 20, contrast = 12, warmth = 15)),
    DREAM("梦幻", "梦幻效果", listOf("梦幻", "梦境", "童话", "Magic"), CameraParams(saturation = 15, brightness = 10, clarity = 8)),
    ARTISTIC("艺术", "艺术摄影", listOf("艺术", "Fine Art", "创作", "Concept")),
    ABSTRACT("抽象", "抽象摄影", listOf("抽象", "Abstract", "创意", "艺术")),
    SURREAL("超现实", "超现实风格", listOf("超现实", "Surreal", "梦境", "奇幻")),
    POP_ART("波普", "波普艺术", listOf("波普", "Pop Art", "鲜艳", "现代")),
    IMPRESSIONISM("印象派", "印象派风格", listOf("印象派", "Impressionism", "莫奈", "朦胧")),
    EXPRESSIONISM("表现主义", "表现派风格", listOf("表现主义", "Expressionism", "情感", "夸张")),
    SURREALISM("超现实主义", "超现实艺术", listOf("超现实主义", "Surrealism", "梦境")),
    MINIMALISM("极简主义", "极简风格", listOf("极简主义", "Minimalism", "简约", "留白")),
    MAXIMALISM("极繁主义", "极繁风格", listOf("极繁主义", "Maximalism", "丰富", "繁复")),
    GRAPHIC("图形", "图形风格", listOf("图形", "Graphic", "几何", "线条")),
    TYPOGRAPHY("文字", "文字摄影", listOf("文字", "Typography", "字体", "排版")),
    SYMMETRY("对称", "对称构图", listOf("对称", "Symmetry", "镜像", "平衡")),
    ASYMMETRY("不对称", "非对称构图", listOf("不对称", "Asymmetry", "动态")),
    LEADING_LINE("引导线", "线条引导", listOf("引导线", "Leading Line", "透视")),
    FRAMING("框架", "框架构图", listOf("框架", "Framing", "框景", "框中框")),
    RULE_OF_THIRDS("三分法", "三分构图", listOf("三分法", "Rule of Thirds", "网格")),
    CENTER_COMPOSITION("中心构图", "居中构图", listOf("中心构图", "居中", "对称")),
    DIAGONAL("对角线", "对角构图", listOf("对角线", "Diagonal", "斜线")),
    TRIANGLE("三角", "三角构图", listOf("三角", "Triangle", "稳定")),
    CIRCLE("圆形", "圆形构图", listOf("圆形", "Circle", "环形", "包围")),
    LEAF("叶片", "叶片特写", listOf("叶片", "Leaf", "叶脉", "纹理")),
    WATER_DROP("水滴", "水滴微距", listOf("水滴", "Water Drop", "露珠", "反射")),
    LIGHT_BEAM("光束", "光线效果", listOf("光束", "Light Beam", "丁达尔", "阳光")),
    SHADOW("阴影", "阴影效果", listOf("阴影", "Shadow", "光影", "对比")),
    REFLECTION("反射", "反射效果", listOf("反射", "Reflection", "镜像", "水面")),
    REFRACTION("折射", "折射效果", listOf("折射", "Refraction", "棱镜", "彩虹")),
    BOKEH("散景", "焦外虚化", listOf("散景", "Bokeh", "虚化", "光斑")),
    LONG_EXPOSURE("长曝光", "慢门摄影", listOf("长曝光", "Long Exposure", "光轨", "水流")),
    HIGH_SPEED("高速", "高速摄影", listOf("高速", "High Speed", "瞬间", "冻结")),
    HDR_PHOTO("HDR", "高动态范围", listOf("HDR", "高动态", "明暗", "细节")),
    PANORAMA("全景", "全景摄影", listOf("全景", "Panorama", "广角", "拼接")),
    TIME_LAPSE("延时", "延时摄影", listOf("延时", "Time Lapse", "变化", "流逝")),
    STAR_TRAIL("星轨", "星星轨迹", listOf("星轨", "Star Trail", "长时间曝光", "星空")),
    LIGHT_PAINTING("光绘", "光绘摄影", listOf("光绘", "Light Painting", "涂鸦", "光")),
    DOUBLE_EXPOSURE("双重曝光", "多重曝光", listOf("双重曝光", "Double Exposure", "叠加")),
    INFRARED("红外", "红外摄影", listOf("红外", "Infrared", "红外滤镜", "特殊")),
    UV_PHOTOGRAPHY("紫外", "紫外摄影", listOf("紫外", "UV", "紫外线", "荧光")),
    PINHOLE("针孔", "针孔摄影", listOf("针孔", "Pinhole", "小孔成像", "复古")),
    TILT_SHIFT("移轴", "移轴摄影", listOf("移轴", "Tilt Shift", "微缩模型", "模糊")),

    // ==================== 其他类（50种） ====================
    DOCUMENTARY("纪实", "纪实摄影", listOf("纪实", "记录", "Documentary"), CameraParams(contrast = 10, saturation = 5, clarity = 8)),
    SPORTS("运动", "运动摄影", listOf("运动", "体育", "足球", "篮球"), CameraParams(shutter_speed = "1/1000", ai_scene = true)),
    CAR("汽车", "汽车摄影", listOf("汽车", "车", "跑车", "Car"), CameraParams(contrast = 15, clarity = 12, hdr = true)),
    PRODUCT("产品", "产品摄影", listOf("产品", "商品", "电商", "Product"), CameraParams(contrast = 12, saturation = 10, clarity = 15)),
    DOCUMENT("文档", "文档扫描", listOf("文档", "文件", "文字", "扫描"), CameraParams(contrast = 20, saturation = 0, clarity = 15)),
    SCREENSHOT("截图", "屏幕截图", listOf("截图", "屏幕", "界面", "UI"), CameraParams(contrast = 10, saturation = 0, brightness = 5)),
    QR_CODE("二维码", "二维码", listOf("二维码", "QR", "码"), CameraParams(contrast = 20, saturation = 0, clarity = 18)),
    XRAY("X光", "X光透视", listOf("X光", "透视", "Medical"), CameraParams(contrast = 25, saturation = 0, brightness = 5)),
    AERIAL("航拍", "无人机航拍", listOf("航拍", "无人机", "上帝视角", "鸟瞰"), CameraParams(contrast = 12, saturation = 10, clarity = 8)),
    UNKNOWN("智能识别", "AI自动识别", listOf("未知", "自动", "智能"), CameraParams(ai_scene = true)),
    SPORTS_FOOTBALL("足球", "足球摄影", listOf("足球", "Football", "Soccer", "球场")),
    SPORTS_BASKETBALL("篮球", "篮球摄影", listOf("篮球", "Basketball", "NBA", "球场")),
    SPORTS_TENNIS("网球", "网球摄影", listOf("网球", "Tennis", "球场", "球拍")),
    SPORTS_GOLF("高尔夫", "高尔夫摄影", listOf("高尔夫", "Golf", "球场", "球杆")),
    SPORTS_SWIMMING("游泳", "游泳摄影", listOf("游泳", "Swimming", "泳池", "泳衣")),
    SPORTS_RUNNING("跑步", "跑步摄影", listOf("跑步", "Running", "马拉松", "运动")),
    SPORTS_CYCLING("骑行", "骑行摄影", listOf("骑行", "Cycling", "自行车", "公路")),
    SPORTS_SKIING("滑雪", "滑雪摄影", listOf("滑雪", "Skiing", "雪场", "单板")),
    SPORTS_SNOWBOARD("单板", "单板滑雪", listOf("单板", "Snowboard", "极限", "雪")),
    SPORTS_SURFING("冲浪", "冲浪摄影", listOf("冲浪", "Surfing", "海浪", "板")),
    SPORTS_SKATEBOARD("滑板", "滑板摄影", listOf("滑板", "Skateboard", "极限", "街头")),
    SPORTS_PARKOUR("跑酷", "跑酷摄影", listOf("跑酷", "Parkour", "极限", "城市")),
    SPORTS_DANCE("舞蹈", "舞蹈摄影", listOf("舞蹈", "Dance", "芭蕾", "街舞")),
    SPORTS_GYM("健身", "健身摄影", listOf("健身", "Gym", "肌肉", "锻炼")),
    SPORTS_YOGA("瑜伽", "瑜伽摄影", listOf("瑜伽", "Yoga", "冥想", "拉伸")),
    CAR_SPORTS("跑车", "跑车摄影", listOf("跑车", "Sports Car", "超跑", "性能")),
    CAR_LUXURY("豪车", "豪华车", listOf("豪车", "Luxury Car", "高端", "品牌")),
    CAR_VINTAGE("老爷车", "复古车", listOf("老爷车", "Vintage Car", "经典", "古董")),
    CAR_ELECTRIC("电动车", "电动汽车", listOf("电动车", "Electric Car", "新能源", "Tesla")),
    CAR_OFFROAD("越野车", "越野汽车", listOf("越野车", "Offroad", "SUV", "四驱")),
    CAR_RACING("赛车", "赛车", listOf("赛车", "Racing", "F1", "赛道")),
    PRODUCT_ELECTRONICS("电子产品", "电子数码", listOf("电子产品", "手机", "电脑", "数码")),
    PRODUCT_FASHION("时尚产品", "时尚配饰", listOf("时尚产品", "服装", "包包", "首饰")),
    PRODUCT_COSMETICS("美妆产品", "化妆品", listOf("美妆产品", "化妆品", "护肤品", "彩妆")),
    PRODUCT_FOOD("食品产品", "食品包装", listOf("食品产品", "包装", "零食", "饮料")),
    PRODUCT_HOME("家居产品", "家居用品", listOf("家居产品", "家具", "装饰", "用品")),
    PRODUCT_TOY("玩具产品", "玩具", listOf("玩具产品", "玩具", "儿童", "益智")),
    DOCUMENT_ID("证件", "证件拍摄", listOf("证件", "身份证", "护照", "驾照")),
    DOCUMENT_CONTRACT("合同", "合同文档", listOf("合同", "协议", "文件", "签名")),
    DOCUMENT_NOTE("笔记", "手写笔记", listOf("笔记", "手写", "便签", "Memo")),
    DOCUMENT_BOOK("书籍", "书籍文档", listOf("书籍", "书本", "阅读", "Page")),
    DOCUMENT_NEWSPAPER("报纸", "报纸文档", listOf("报纸", "新闻", "报刊", "头条")),
    SCREEN_APP("应用界面", "APP界面", listOf("应用界面", "APP", "UI", "界面")),
    SCREEN_WEB("网页界面", "网页截图", listOf("网页界面", "Website", "Web", "截图")),
    SCREEN_GAME("游戏界面", "游戏截图", listOf("游戏界面", "Game", "游戏", "UI")),
    SCREEN_VIDEO("视频画面", "视频截图", listOf("视频画面", "Video", "电影", "截图")),
    AERIAL_BUILDING("建筑航拍", "建筑鸟瞰", listOf("建筑航拍", "Building", "鸟瞰")),
    AERIAL_LANDSCAPE("风景航拍", "风景鸟瞰", listOf("风景航拍", "Landscape", "上帝视角")),
    AERIAL_EVENT("活动航拍", "活动鸟瞰", listOf("活动航拍", "Event", "人群", "集会")),
    AERIAL_CITY("城市航拍", "城市鸟瞰", listOf("城市航拍", "City", "全景")),

    // ==================== 新增扩展场景（140种） ====================
    // 人像扩展
    PORTRAIT_DUAL("双人像", "双人合影", listOf("双人", "情侣", "姐妹", "兄弟")),
    PORTRAIT_TRIOS("三人像", "三人合影", listOf("三人", "闺蜜", "兄弟")),
    PORTRAIT_GROUP_LARGE("多人像", "多人合影", listOf("多人", "团队", "集体")),
    PORTRAIT_WORKING("工作照", "工作场景", listOf("工作照", "职业照", "工位")),
    PORTRAIT_CASUAL("休闲照", "休闲风格", listOf("休闲", "日常", "生活")),
    PORTRAIT_FORMAL("正装照", "正式场合", listOf("正装", "西装", "礼服")),
    PORTRAIT_CASUAL_STYLE("随性", "随性风格", listOf("随性", "自由", "自然")),
    PORTRAIT_ARTISTIC_POSE("艺术摆拍", "艺术姿势", listOf("摆拍", "Pose", "艺术")),
    PORTRAIT_CANDID("抓拍", "抓拍瞬间", listOf("抓拍", "Candid", "瞬间")),
    PORTRAIT_EXPRESSION("表情", "表情特写", listOf("表情", "Emotion", "喜怒哀乐")),
    PORTRAIT_HAND("手部", "手部特写", listOf("手", "手部", "手势", "细节")),
    PORTRAIT_FACE("面部", "面部特写", listOf("面部", "Face", "五官")),
    PORTRAIT_EYES("眼睛", "眼睛特写", listOf("眼睛", "Eyes", "眼神")),
    PORTRAIT_LIPS("嘴唇", "嘴唇特写", listOf("嘴唇", "Lips", "唇")),
    PORTRAIT_HAIR("发型", "发型特写", listOf("发型", "Hair", "头发")),
    PORTRAIT_JEWELRY("饰品", "饰品特写", listOf("饰品", "Jewelry", "配饰")),
    PORTRAIT_CLOTHING("服装", "服装细节", listOf("服装", "Clothing", "穿搭")),
    PORTRAIT_ACCESSORIES("配饰", "配饰细节", listOf("配饰", "Accessories", "包包")),
    PORTRAIT_SHOES("鞋子", "鞋子特写", listOf("鞋子", "Shoes", "鞋")),
    PORTRAIT_HAT("帽子", "帽子特写", listOf("帽子", "Hat", "头饰")),
    // 风景扩展
    LANDSCAPE_SUNRISE_MOUNTAIN("山巅日出", "山顶日出", listOf("山巅日出", "山顶朝阳")),
    LANDSCAPE_SUNSET_OCEAN("海上日落", "海边夕阳", listOf("海上日落", "海边黄昏")),
    LANDSCAPE_FOG_MOUNTAIN("雾中山景", "云雾山峰", listOf("雾中山", "云海")),
    LANDSCAPE_SNOW_MOUNTAIN("雪山风光", "雪山风景", listOf("雪山", "雪峰")),
    LANDSCAPE_DESERT_DUNE("沙漠沙丘", "沙丘曲线", listOf("沙丘", "沙漠曲线")),
    LANDSCAPE_ICE_CAVE("冰洞", "冰洞景观", listOf("冰洞", "冰穴", "蓝冰")),
    LANDSCAPE_CAVE("溶洞", "溶洞景观", listOf("溶洞", "钟乳石", "地下")),
    LANDSCAPE_GEYSER("间歇泉", "地热喷泉", listOf("间歇泉", "Geyser", "地热")),
    LANDSCAPE_WATERFALL_UNDER("瀑布下方", "瀑布底部", listOf("瀑布下", "水帘洞")),
    LANDSCAPE_COAST_ROCK("海岸礁石", "礁石海景", listOf("礁石", "海岸岩石")),
    LANDSCAPE_TIDAL_POOL("潮池", "潮间带", listOf("潮池", "Tidal Pool", "海洋生物")),
    LANDSCAPE_SALT_FLAT("盐滩", "盐沼景观", listOf("盐滩", "Salt Flat", "天空之镜")),
    LANDSCAPE_MANGROVE("红树林", "红树林景观", listOf("红树林", "Mangrove", "湿地")),
    LANDSCAPE_BAMBOO_FOREST("竹林", "竹林景观", listOf("竹林", "Bamboo", "翠绿")),
    LANDSCAPE_CACTUS("仙人掌", "仙人掌景观", listOf("仙人掌", "Cactus", "沙漠")),
    LANDSCAPE_PALM("棕榈树", "棕榈景观", listOf("棕榈树", "Palm", "热带")),
    LANDSCAPE_COTTON_FIELD("棉田", "棉花田", listOf("棉田", "棉花", "白色")),
    LANDSCAPE_SUNFLOWER("向日葵", "向日葵田", listOf("向日葵", "Sunflower", "黄色")),
    LANDSCAPE_TULIP("郁金香", "郁金香田", listOf("郁金香", "Tulip", "花海")),
    LANDSCAPE_LAVENDER("薰衣草", "薰衣草田", listOf("薰衣草", "Lavender", "紫色")),
    // 城市扩展
    CITY_ALLEYWAY("小巷", "城市小巷", listOf("小巷", "Alley", "胡同")),
    CITY_ROOFTOP("屋顶", "屋顶风景", listOf("屋顶", "Rooftop", "天台")),
    CITY_SUBWAY("地铁", "地铁场景", listOf("地铁", "Subway", "地下")),
    CITY_TRAIN_STATION("火车站", "火车站台", listOf("火车站", "Train Station", "站台")),
    CITY_AIRPORT("机场", "机场场景", listOf("机场", "Airport", "航站楼")),
    CITY_FERRY("渡轮", "渡轮场景", listOf("渡轮", "Ferry", "船")),
    CITY_BUS("公交", "公交车内", listOf("公交", "Bus", "车内")),
    CITY_TAXI("出租车", "出租车内", listOf("出租车", "Taxi", "车内")),
    CITY_BIKE("自行车", "城市骑行", listOf("自行车", "Bike", "骑行")),
    CITY_PEDESTRIAN("行人", "行人街道", listOf("行人", "Pedestrian", "街道")),
    CITY_NEON_ALLEY("霓虹小巷", "霓虹灯小巷", listOf("霓虹小巷", "Night Alley")),
    CITY_RAINY_NIGHT("雨夜", "雨中夜景", listOf("雨夜", "Rainy Night", "倒影")),
    CITY_SNOW_NIGHT("雪夜", "雪中夜景", listOf("雪夜", "Snowy Night", "白色")),
    CITY_FOG_NIGHT("雾夜", "雾中夜景", listOf("雾夜", "Foggy Night", "朦胧")),
    CITY_LIGHT_TRAIL("光轨", "车流光轨", listOf("光轨", "Light Trail", "长曝光")),
    CITY_FIREWORKS("烟花", "城市烟花", listOf("烟花", "Fireworks", "庆典")),
    CITY_FESTIVAL("节日", "节日装饰", listOf("节日", "Festival", "装饰")),
    CITY_CHRISTMAS("圣诞", "圣诞装饰", listOf("圣诞", "Christmas", "节日")),
    CITY_NEW_YEAR("新年", "新年场景", listOf("新年", "New Year", "烟花")),
    CITY_LANTERN("灯笼", "灯笼装饰", listOf("灯笼", "Lantern", "节日")),
    // 美食扩展
    FOOD_BREAKFAST("早餐", "早餐美食", listOf("早餐", "Breakfast", "早晨")),
    FOOD_LUNCH("午餐", "午餐美食", listOf("午餐", "Lunch", "中午")),
    FOOD_DINNER("晚餐", "晚餐美食", listOf("晚餐", "Dinner", "晚上")),
    FOOD_SNACK("小吃", "街头小吃", listOf("小吃", "Snack", "街头")),
    FOOD_FINGER("手抓", "手抓食物", listOf("手抓", "Finger Food", "便捷")),
    FOOD_FUSION("融合菜", "融合料理", listOf("融合菜", "Fusion", "创意")),
    FOOD_GOURMET("美食家", "高端料理", listOf("美食家", "Gourmet", "高端")),
    FOOD_HOMEMADE("家常菜", "家常料理", listOf("家常菜", "Homemade", "温馨")),
    FOOD_STREET("街头美食", "路边摊", listOf("街头美食", "Street Food", "路边")),
    FOOD_FARM_TO_TABLE("农场直供", "农场餐桌", listOf("农场直供", "Farm to Table")),
    FOOD_VEGAN("素食", "纯素料理", listOf("素食", "Vegan", "植物")),
    FOOD_VEGETARIAN("素食", "素食料理", listOf("素食", "Vegetarian", "蔬菜")),
    FOOD_GLUTEN_FREE("无麸质", "无麸质食品", listOf("无麸质", "Gluten Free")),
    FOOD_ORGANIC("有机", "有机食品", listOf("有机", "Organic", "天然")),
    FOOD_RAW("生食", "生食料理", listOf("生食", "Raw", "新鲜")),
    FOOD_GRILL("烧烤", "炭火烧烤", listOf("烧烤", "Grill", "炭火")),
    FOOD_STEAM("蒸制", "蒸菜", listOf("蒸制", "Steam", "健康")),
    FOOD_FRY("油炸", "油炸食品", listOf("油炸", "Fried", "酥脆")),
    FOOD_BAKE("烘焙", "烘焙食品", listOf("烘焙", "Bake", "烤箱")),
    FOOD_BOIL("水煮", "水煮食品", listOf("水煮", "Boil", "清淡")),
    // 自然生态扩展
    WILDLIFE_BEAR("熊", "熊类", listOf("熊", "Bear", "北极熊", "棕熊")),
    WILDLIFE_LION("狮子", "狮子", listOf("狮子", "Lion", "王者", "草原")),
    WILDLIFE_TIGER("老虎", "老虎", listOf("老虎", "Tiger", "百兽之王")),
    WILDLIFE_ELEPHANT("大象", "大象", listOf("大象", "Elephant", "庞大")),
    WILDLIFE_GIRAFFE("长颈鹿", "长颈鹿", listOf("长颈鹿", "Giraffe", "高")),
    WILDLIFE_ZEBRA("斑马", "斑马", listOf("斑马", "Zebra", "条纹")),
    WILDLIFE_GORILLA("大猩猩", "大猩猩", listOf("大猩猩", "Gorilla", "猿")),
    WILDLIFE_CHEETAH("猎豹", "猎豹", listOf("猎豹", "Cheetah", "最快")),
    WILDLIFE_WOLF("狼", "狼", listOf("狼", "Wolf", "狼群")),
    WILDLIFE_FOX("狐狸", "狐狸", listOf("狐狸", "Fox", "狡猾")),
    WILDLIFE_DEER("鹿", "鹿", listOf("鹿", "Deer", "优雅")),
    WILDLIFE_RABBIT("兔子", "兔子", listOf("兔子", "Rabbit", "可爱")),
    WILDLIFE_OWL("猫头鹰", "猫头鹰", listOf("猫头鹰", "Owl", "智慧")),
    WILDLIFE_EAGLE("鹰", "鹰", listOf("鹰", "Eagle", "猛禽")),
    WILDLIFE_DOLPHIN("海豚", "海豚", listOf("海豚", "Dolphin", "聪明")),
    WILDLIFE_WHALE("鲸鱼", "鲸鱼", listOf("鲸鱼", "Whale", "巨大")),
    WILDLIFE_SHARK("鲨鱼", "鲨鱼", listOf("鲨鱼", "Shark", "凶猛")),
    WILDLIFE_TURTLE("海龟", "海龟", listOf("海龟", "Turtle", "长寿")),
    WILDLIFE_FROG("青蛙", "青蛙", listOf("青蛙", "Frog", "跳跃")),
    WILDLIFE_BUTTERFLY("蝴蝶", "蝴蝶", listOf("蝴蝶", "Butterfly", "美丽")),
    // 创意扩展
    CREATIVE_LENS_FLARE("镜头眩光", "眩光效果", listOf("眩光", "Lens Flare", "光线")),
    CREATIVE_CHROMATIC_ABERRATION("色差", "色边效果", listOf("色差", "Chromatic Aberration")),
    CREATIVE_VIGNETTE("暗角", "暗角效果", listOf("暗角", "Vignette", "边角")),
    CREATIVE_GRAIN("颗粒", "胶片颗粒", listOf("颗粒", "Grain", "Film")),
    CREATIVE_NOISE("噪点", "噪点效果", listOf("噪点", "Noise", "质感")),
    CREATIVE_SOFT_FOCUS("柔焦", "柔焦效果", listOf("柔焦", "Soft Focus", "朦胧")),
    CREATIVE_SHARPEN("锐化", "锐化效果", listOf("锐化", "Sharpen", "清晰")),
    CREATIVE_BLUR("模糊", "模糊效果", listOf("模糊", "Blur", "虚化")),
    CREATIVE_MOTION_BLUR("运动模糊", "动态模糊", listOf("运动模糊", "Motion Blur")),
    CREATIVE_RADIAL_BLUR("径向模糊", "放射模糊", listOf("径向模糊", "Radial Blur")),
    CREATIVE_ZOOM_BLUR("缩放模糊", "变焦模糊", listOf("缩放模糊", "Zoom Blur")),
    CREATIVE_COLOR_GRADING("调色", "色彩分级", listOf("调色", "Color Grading", "LUT")),
    CREATIVE_TONING("色调", "色调调整", listOf("色调", "Toning", "单色调")),
    CREATIVE_SPLIT_TONING("分离色调", "双色调", listOf("分离色调", "Split Toning")),
    CREATIVE_GRADIENT_MAP("渐变映射", "渐变调色", listOf("渐变映射", "Gradient Map")),
    CREATIVE_CURVES("曲线", "曲线调整", listOf("曲线", "Curves", "色调曲线")),
    CREATIVE_LEVELS("色阶", "色阶调整", listOf("色阶", "Levels", "对比度")),
    CREATIVE_EXPOSURE("曝光", "曝光调整", listOf("曝光", "Exposure", "亮度")),
    CREATIVE_CONTRAST("对比度", "对比度调整", listOf("对比度", "Contrast")),
    CREATIVE_SATURATION("饱和度", "饱和度调整", listOf("饱和度", "Saturation")),
    CREATIVE_BRIGHTNESS("亮度", "亮度调整", listOf("亮度", "Brightness")),
    CREATIVE_WARMTH("色温", "色温调整", listOf("色温", "Warmth", "色调")),
    CREATIVE_TINT("色调", "色调调整", listOf("色调", "Tint", "偏色")),
    CREATIVE_HUE("色相", "色相调整", listOf("色相", "Hue", "颜色")),
    CREATIVE_SHADOWS("阴影", "阴影调整", listOf("阴影", "Shadows", "暗部")),
    CREATIVE_HIGHLIGHTS("高光", "高光调整", listOf("高光", "Highlights", "亮部")),
    CREATIVE_BLACKS("黑场", "黑场调整", listOf("黑场", "Blacks", "暗调")),
    CREATIVE_WHITES("白场", "白场调整", listOf("白场", "Whites", "亮调")),
    CREATIVE_CLARITY("清晰度", "清晰度调整", listOf("清晰度", "Clarity", "细节")),
    // 科技数码扩展
    TECH_SMARTPHONE("手机", "手机摄影", listOf("手机", "Smartphone", "Phone")),
    TECH_CAMERA("相机", "相机摄影", listOf("相机", "Camera", "DSLR")),
    TECH_LAPTOP("笔记本", "笔记本电脑", listOf("笔记本", "Laptop", "电脑")),
    TECH_TABLET("平板", "平板电脑", listOf("平板", "Tablet", "iPad")),
    TECH_WATCH("手表", "智能手表", listOf("手表", "Watch", "Smartwatch")),
    TECH_EARPHONES("耳机", "耳机", listOf("耳机", "Earphones", "Audio")),
    TECH_SPEAKER("音箱", "音响", listOf("音箱", "Speaker", "Sound")),
    TECH_MONITOR("显示器", "显示器", listOf("显示器", "Monitor", "屏幕")),
    TECH_KEYBOARD("键盘", "键盘", listOf("键盘", "Keyboard", "输入")),
    TECH_MOUSE("鼠标", "鼠标", listOf("鼠标", "Mouse", "指针")),
    TECH_PRINTER("打印机", "打印机", listOf("打印机", "Printer", "打印")),
    TECH_SCANNER("扫描仪", "扫描仪", listOf("扫描仪", "Scanner", "扫描")),
    TECH_ROUTER("路由器", "路由器", listOf("路由器", "Router", "网络")),
    TECH_MODERN("调制解调器", "Modem", listOf("调制解调器", "Modem", "上网")),
    TECH_BATTERY("充电宝", "移动电源", listOf("充电宝", "Power Bank", "充电")),
    TECH_CABLE("数据线", "数据线", listOf("数据线", "Cable", "连接")),
    TECH_ADAPTER("适配器", "适配器", listOf("适配器", "Adapter", "转换")),
    TECH_CASE("保护壳", "保护套", listOf("保护壳", "Case", "保护")),
    TECH_SCREEN_PROTECTOR("贴膜", "屏幕保护膜", listOf("贴膜", "Screen Protector")),
    TECH_STAND("支架", "支架", listOf("支架", "Stand", "支撑")),
    // 生活方式扩展
    LIFESTYLE_TRAVEL("旅行", "旅行摄影", listOf("旅行", "Travel", "旅程")),
    LIFESTYLE_HOLIDAY("假期", "假期生活", listOf("假期", "Holiday", "休闲")),
    LIFESTYLE_WORK("工作", "工作场景", listOf("工作", "Work", "职场")),
    LIFESTYLE_STUDY("学习", "学习场景", listOf("学习", "Study", "学生")),
    LIFESTYLE_READING("阅读", "阅读场景", listOf("阅读", "Reading", "书籍")),
    LIFESTYLE_COOKING("烹饪", "烹饪场景", listOf("烹饪", "Cooking", "厨房")),
    LIFESTYLE_CLEANING("清洁", "清洁场景", listOf("清洁", "Cleaning", "打扫")),
    LIFESTYLE_SHOPPING("购物", "购物场景", listOf("购物", "Shopping", "商场")),
    LIFESTYLE_CAFE("咖啡", "咖啡馆", listOf("咖啡", "Cafe", "休闲")),
    LIFESTYLE_BAR("酒吧", "酒吧场景", listOf("酒吧", "Bar", "夜生活")),
    LIFESTYLE_FITNESS("健身", "健身场景", listOf("健身", "Fitness", "运动")),
    LIFESTYLE_MEDITATION("冥想", "冥想场景", listOf("冥想", "Meditation", "放松")),
    LIFESTYLE_SLEEP("睡眠", "睡眠场景", listOf("睡眠", "Sleep", "休息")),
    LIFESTYLE_PARTY("派对", "派对场景", listOf("派对", "Party", "庆祝")),
    LIFESTYLE_GATHERING("聚会", "聚会场景", listOf("聚会", "Gathering", "朋友")),
    LIFESTYLE_PICNIC("野餐", "野餐场景", listOf("野餐", "Picnic", "户外")),
    LIFESTYLE_CAMPING("露营", "露营场景", listOf("露营", "Camping", "户外")),
    LIFESTYLE_HIKING("徒步", "徒步场景", listOf("徒步", "Hiking", "登山")),
    LIFESTYLE_FISHING("钓鱼", "钓鱼场景", listOf("钓鱼", "Fishing", "休闲")),
    LIFESTYLE_GARDENING("园艺", "园艺场景", listOf("园艺", "Gardening", "植物")),
    // 艺术文化扩展
    ART_MUSEUM("博物馆", "博物馆场景", listOf("博物馆", "Museum", "展览")),
    ART_GALLERY("美术馆", "美术馆场景", listOf("美术馆", "Gallery", "艺术")),
    ART_THEATER("剧院", "剧院场景", listOf("剧院", "Theater", "演出")),
    ART_CONCERT("音乐会", "音乐会场景", listOf("音乐会", "Concert", "音乐")),
    ART_OPERA("歌剧", "歌剧场景", listOf("歌剧", "Opera", "表演")),
    ART_BALLET("芭蕾", "芭蕾舞", listOf("芭蕾", "Ballet", "舞蹈")),
    ART_DANCE("舞蹈", "舞蹈表演", listOf("舞蹈", "Dance", "表演")),
    ART_MUSICAL("音乐剧", "音乐剧", listOf("音乐剧", "Musical", "歌舞")),
    ART_EXHIBITION("展览", "展览场景", listOf("展览", "Exhibition", "展示")),
    ART_FAIR("艺术博览会", "艺术展", listOf("艺术博览会", "Art Fair", "展会")),
    ART_STUDIO("工作室", "艺术工作室", listOf("工作室", "Studio", "创作")),
    ART_CLASS("艺术课", "艺术课程", listOf("艺术课", "Art Class", "学习")),
    ART_PAINTING("绘画", "绘画艺术", listOf("绘画", "Painting", "画笔")),
    ART_SCULPTURE("雕塑", "雕塑艺术", listOf("雕塑", "Sculpture", "立体")),
    ART_PHOTOGRAPHY("摄影", "摄影艺术", listOf("摄影", "Photography", "镜头")),
    ART_CALLIGRAPHY("书法", "书法艺术", listOf("书法", "Calligraphy", "笔墨")),
    ART_CRAFT("手工艺", "手工艺", listOf("手工艺", "Craft", "手工")),
    ART_POTTERY("陶艺", "陶艺艺术", listOf("陶艺", "Pottery", "陶瓷")),
    ART_WEAVING("编织", "编织艺术", listOf("编织", "Weaving", "纺织")),
    ART_JEWELRY_MAKING("珠宝制作", "珠宝工艺", listOf("珠宝制作", "Jewelry Making")),
    // 历史古迹扩展
    HISTORY_ANCIENT("古迹", "古代遗迹", listOf("古迹", "Ancient", "历史")),
    HISTORY_TEMPLE("寺庙", "寺庙古迹", listOf("寺庙", "Temple", "宗教")),
    HISTORY_PALACE("宫殿", "宫殿建筑", listOf("宫殿", "Palace", "皇家")),
    HISTORY_CASTLE("城堡", "城堡建筑", listOf("城堡", "Castle", "中世纪")),
    HISTORY_FORTRESS("堡垒", "堡垒建筑", listOf("堡垒", "Fortress", "防御")),
    HISTORY_MONUMENT("古迹", "历史遗迹", listOf("古迹", "Monument", "纪念")),
    HISTORY_ARCHAEOLOGY("考古", "考古现场", listOf("考古", "Archaeology", "发掘")),
    HISTORY_RELIC("文物", "文物古董", listOf("文物", "Relic", "古董")),
    HISTORY_MUMMY("木乃伊", "木乃伊", listOf("木乃伊", "Mummy", "古埃及")),
    HISTORY_PYRAMID("金字塔", "金字塔", listOf("金字塔", "Pyramid", "埃及")),
    HISTORY_STONEHENGE("巨石阵", "巨石阵", listOf("巨石阵", "Stonehenge", "神秘")),
    HISTORY_MACHU_PICCHU("马丘比丘", "马丘比丘", listOf("马丘比丘", "Machu Picchu")),
    HISTORY_TERRA_COTTA("兵马俑", "兵马俑", listOf("兵马俑", "Terra Cotta", "中国")),
    HISTORY_GREAT_WALL("长城", "长城", listOf("长城", "Great Wall", "中国")),
    HISTORY_TAJ_MAHAL("泰姬陵", "泰姬陵", listOf("泰姬陵", "Taj Mahal", "印度")),
    HISTORY_COLOSSEUM("斗兽场", "罗马斗兽场", listOf("斗兽场", "Colosseum", "罗马")),
    HISTORY_PARTHEON("帕特农神庙", "帕特农神庙", listOf("帕特农神庙", "Parthenon")),
    HISTORY_ACROPOLIS("卫城", "雅典卫城", listOf("卫城", "Acropolis", "希腊")),
    HISTORY_ANGKOR("吴哥窟", "吴哥窟", listOf("吴哥窟", "Angkor", "柬埔寨")),
    HISTORY_PETRA("佩特拉", "佩特拉古城", listOf("佩特拉", "Petra", "约旦")),
    // 节日庆典扩展
    FESTIVAL_SPRING_FESTIVAL("春节", "中国新年", listOf("春节", "Spring Festival", "过年")),
    FESTIVAL_LANTERN("元宵节", "元宵节", listOf("元宵节", "Lantern Festival", "灯")),
    FESTIVAL_QINGMING("清明节", "清明节", listOf("清明节", "Qingming", "扫墓")),
    FESTIVAL_DRAGON_BOAT("端午节", "端午节", listOf("端午节", "Dragon Boat", "粽子")),
    FESTIVAL_MID_AUTUMN("中秋节", "中秋节", listOf("中秋节", "Mid Autumn", "月亮")),
    FESTIVAL_DOUBLE_NINTH("重阳节", "重阳节", listOf("重阳节", "Double Ninth", "登高")),
    FESTIVAL_CHRISTMAS("圣诞节", "圣诞节", listOf("圣诞节", "Christmas", "耶稣")),
    FESTIVAL_NEW_YEAR("元旦", "新年", listOf("元旦", "New Year", "1月1日")),
    FESTIVAL_VALENTINE("情人节", "情人节", listOf("情人节", "Valentine", "爱情")),
    FESTIVAL_EASTER("复活节", "复活节", listOf("复活节", "Easter", "兔子")),
    FESTIVAL_HALLOWEEN("万圣节", "万圣节", listOf("万圣节", "Halloween", "南瓜")),
    FESTIVAL_THANKSGIVING("感恩节", "感恩节", listOf("感恩节", "Thanksgiving", "感恩")),
    FESTIVAL_INDEPENDENCE("独立日", "独立日", listOf("独立日", "Independence Day")),
    FESTIVAL_DIWALI("排灯节", "排灯节", listOf("排灯节", "Diwali", "印度")),
    FESTIVAL_HANUKKAH("光明节", "光明节", listOf("光明节", "Hanukkah", "犹太")),
    FESTIVAL_RAMADAN("斋月", "斋月", listOf("斋月", "Ramadan", "伊斯兰")),
    FESTIVAL_EWOK("春节", "春节", listOf("春节", "Lunar New Year", "农历")),
    FESTIVAL_CARNIVAL("狂欢节", "狂欢节", listOf("狂欢节", "Carnival", "派对")),
    FESTIVAL_OKTOBERFEST("啤酒节", "啤酒节", listOf("啤酒节", "Oktoberfest", "德国")),
    FESTIVAL_SANTA("圣诞老人", "圣诞老人", listOf("圣诞老人", "Santa Claus", "礼物")),
    // 天气现象扩展
    WEATHER_SUNNY("晴天", "晴朗天气", listOf("晴天", "Sunny", "阳光")),
    WEATHER_CLOUDY("多云", "多云天气", listOf("多云", "Cloudy", "阴天")),
    WEATHER_OVERCAST("阴天", "阴天天气", listOf("阴天", "Overcast", "阴暗")),
    WEATHER_RAIN("雨天", "下雨天气", listOf("雨天", "Rainy", "下雨")),
    WEATHER_THUNDER("雷雨", "雷雨天气", listOf("雷雨", "Thunderstorm", "闪电")),
    WEATHER_SNOW("雪天", "下雪天气", listOf("雪天", "Snowy", "下雪")),
    WEATHER_FOG("雾天", "雾天", listOf("雾天", "Foggy", "雾气")),
    WEATHER_MIST("薄雾", "薄雾天气", listOf("薄雾", "Misty", "轻雾")),
    WEATHER_HAIL("冰雹", "冰雹天气", listOf("冰雹", "Hail", "冰块")),
    WEATHER_WINDY("大风", "大风天气", listOf("大风", "Windy", "风")),
    WEATHER_DUST("沙尘", "沙尘天气", listOf("沙尘", "Dust", "风沙")),
    WEATHER_SMOG("雾霾", "雾霾天气", listOf("雾霾", "Smog", "污染")),
    WEATHER_FROST("霜冻", "霜冻天气", listOf("霜冻", "Frost", "结冰")),
    WEATHER_DEW("露水", "露水天气", listOf("露水", "Dew", "水珠")),
    WEATHER_RAINBOW("彩虹", "彩虹天气", listOf("彩虹", "Rainbow", "七彩")),
    WEATHER_DOUBLE_RAINBOW("双彩虹", "双道彩虹", listOf("双彩虹", "Double Rainbow")),
    WEATHER_SUNSHOWER("太阳雨", "太阳雨", listOf("太阳雨", "Sunshower", "晴雨")),
    WEATHER_MIRAGE("海市蜃楼", "海市蜃楼", listOf("海市蜃楼", "Mirage", "幻境")),
    WEATHER_AURORA("极光", "极光", listOf("极光", "Aurora", "北极光")),
    WEATHER_METEOR("流星", "流星雨", listOf("流星", "Meteor", "Shooting Star")),
    // 季节时间扩展
    TIME_SPRING("春天", "春季", listOf("春天", "Spring", "春日")),
    TIME_SUMMER("夏天", "夏季", listOf("夏天", "Summer", "夏日")),
    TIME_AUTUMN("秋天", "秋季", listOf("秋天", "Autumn", "秋日")),
    TIME_WINTER("冬天", "冬季", listOf("冬天", "Winter", "冬日")),
    TIME_MORNING("早晨", "上午", listOf("早晨", "Morning", "清晨")),
    TIME_NOON("中午", "正午", listOf("中午", "Noon", "正午")),
    TIME_AFTERNOON("下午", "午后", listOf("下午", "Afternoon", "午后")),
    TIME_EVENING("傍晚", "黄昏", listOf("傍晚", "Evening", "黄昏")),
    TIME_NIGHT("夜晚", "夜间", listOf("夜晚", "Night", "黑夜")),
    TIME_MIDNIGHT("午夜", "子夜", listOf("午夜", "Midnight", "0点")),
    TIME_DAWN("黎明", "拂晓", listOf("黎明", "Dawn", "破晓")),
    TIME_DUSK("黄昏", "薄暮", listOf("黄昏", "Dusk", "暮色")),
    TIME_GOLDEN_HOUR("黄金时刻", "黄金时段", listOf("黄金时刻", "Golden Hour")),
    TIME_BLUE_HOUR("蓝色时刻", "蓝调时段", listOf("蓝色时刻", "Blue Hour")),
    TIME_BLUE_DAWN("蓝色黎明", "黎明蓝调", listOf("蓝色黎明", "Blue Dawn")),
    TIME_BLUE_DUSK("蓝色黄昏", "黄昏蓝调", listOf("蓝色黄昏", "Blue Dusk")),
    TIME_TWILIGHT("暮光", "暮光时分", listOf("暮光", "Twilight", "暮色")),
    TIME_DAY("白天", "日间", listOf("白天", "Day", "白昼")),
    TIME_NIGHTFALL("夜幕", "夜幕降临", listOf("夜幕", "Nightfall", "天黑")),
    TIME_MIDDAY("正午", "中午时分", listOf("正午", "Midday", "12点"))
)