#!/usr/bin/env python3
# Copyright 2026 Yurun Zi
# SPDX-License-Identifier: GPL-3.0-only

from __future__ import annotations

import argparse
import csv
import hashlib
import math
import pathlib
import urllib.request


CIE_CMF_URL = "https://files.cie.co.at/CIE_xyz_1931_2deg.csv"
CIE_CMF_DATASET_DOI = "10.25039/CIE.DS.xvudnb9b"
SECOND_RADIATION_CONSTANT_NM_K = 1.438776877e7


def load_cmf(csv_path: pathlib.Path | None) -> tuple[list[tuple[float, float, float, float]], str]:
    if csv_path is None:
        with urllib.request.urlopen(CIE_CMF_URL, timeout=30) as response:
            data = response.read()
        source = CIE_CMF_URL
    else:
        data = csv_path.read_bytes()
        source = str(csv_path)

    cmf: list[tuple[float, float, float, float]] = []
    for row in csv.reader(data.decode("utf-8").splitlines()):
        if len(row) != 4:
            continue
        wavelength_nm = float(row[0])
        x_bar = float(row[1])
        y_bar = float(row[2])
        z_bar = float(row[3])
        cmf.append((wavelength_nm, x_bar, y_bar, z_bar))

    if not cmf:
        raise RuntimeError("No CIE 1931 CMF rows were loaded.")

    digest = hashlib.md5(data).hexdigest()
    return cmf, f"{source} (md5 {digest})"


def blackbody_uv(cct: float, cmf: list[tuple[float, float, float, float]]) -> tuple[float, float]:
    X = 0.0
    Y = 0.0
    Z = 0.0

    for wavelength_nm, x_bar, y_bar, z_bar in cmf:
        exponent = SECOND_RADIATION_CONSTANT_NM_K / (wavelength_nm * cct)
        spectral_weight = 1.0 / (math.pow(wavelength_nm, 5.0) * math.expm1(exponent))
        X += spectral_weight * x_bar
        Y += spectral_weight * y_bar
        Z += spectral_weight * z_bar

    den = X + 15.0 * Y + 3.0 * Z
    if not math.isfinite(den) or abs(den) <= 1e-30:
        raise RuntimeError(f"Degenerate XYZ integration at {cct:.6f}K")

    u = 4.0 * X / den
    v = 6.0 * Y / den
    return u, v


def build_cct_values(min_cct: float, max_cct: float, step_ratio: float) -> list[float]:
    values: list[float] = []
    cct = min_cct
    while cct < max_cct:
        values.append(cct)
        cct *= step_ratio
    if not values or not math.isclose(values[-1], max_cct):
        values.append(max_cct)
    return values


def render_header(
    entries: list[tuple[float, float, float]],
    source: str,
    min_cct: float,
    max_cct: float,
    step_ratio: float,
) -> str:
    lines = [
        "// Copyright 2026 Yurun Zi",
        "// SPDX-License-Identifier: GPL-3.0-only",
        "//",
        "// Generated by scripts/generate_planckian_locus_table.py.",
        "// Source CMF: CIE 1931 2 degree observer, 1 nm, CIE 018:2019 Table 6.",
        f"// Dataset DOI: {CIE_CMF_DATASET_DOI}",
        f"// Input: {source}",
        "",
        "#pragma once",
        "",
        "#include <array>",
        "",
        "namespace alcedo::planckian_locus {",
        "",
        "struct PlanckianLocusEntry {",
        "  double cct_;",
        "  double u_;",
        "  double v_;",
        "};",
        "",
        f"inline constexpr double kMinCct = {min_cct:.1f};",
        f"inline constexpr double kMaxCct = {max_cct:.1f};",
        f"inline constexpr double kStepRatio = {step_ratio:.8f};",
        "",
        f"inline constexpr std::array<PlanckianLocusEntry, {len(entries)}> kUvTable = {{{{",
    ]

    for cct, u, v in entries:
        lines.append(f"    PlanckianLocusEntry{{{cct:.9f}, {u:.12f}, {v:.12f}}},")

    lines.extend(
        [
            "}};",
            "",
            "}  // namespace alcedo::planckian_locus",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a blackbody Planckian locus uv table.")
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=pathlib.Path(
            "alcedo_studio/src/include/edit/operators/basic/planckian_locus_table.hpp"
        ),
    )
    parser.add_argument("--cie-cmf-csv", type=pathlib.Path)
    parser.add_argument("--min-cct", type=float, default=1000.0)
    parser.add_argument("--max-cct", type=float, default=20000.0)
    parser.add_argument("--step-ratio", type=float, default=1.0025)
    args = parser.parse_args()

    if args.min_cct <= 0.0 or args.max_cct <= args.min_cct:
        raise ValueError("CCT range must be positive and increasing.")
    if args.step_ratio <= 1.0:
        raise ValueError("Step ratio must be greater than 1.0.")

    cmf, source = load_cmf(args.cie_cmf_csv)
    entries = [(cct, *blackbody_uv(cct, cmf)) for cct in build_cct_values(
        args.min_cct, args.max_cct, args.step_ratio
    )]

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        render_header(entries, source, args.min_cct, args.max_cct, args.step_ratio),
        encoding="utf-8",
        newline="\n",
    )
    print(f"Wrote {len(entries)} Planckian locus samples to {args.output}")


if __name__ == "__main__":
    main()
